#include "compiler.h"
#include <stdexcept>

// ─────────────────────────────────────────────
//  Public entry point
// ─────────────────────────────────────────────

CompiledProgram Compiler::compile(ASTNode* root) {
    compileNode(root);
    emitOpcode(Opcode::HALT);
    return CompiledProgram{ std::move(code), std::move(nameTable) };
}

// ─────────────────────────────────────────────
//  Name table
// ─────────────────────────────────────────────

uint16_t Compiler::getOrAddName(const std::string& name) {
    auto it = nameIndex.find(name);
    if (it != nameIndex.end()) return it->second;

    uint16_t idx = static_cast<uint16_t>(nameTable.size());
    nameTable.push_back(name);
    nameIndex[name] = idx;
    return idx;
}

// ─────────────────────────────────────────────
//  Raw byte emission
// ─────────────────────────────────────────────

void Compiler::emit(uint8_t byte) {
    code.push_back(byte);
}

void Compiler::emitOpcode(Opcode op) {
    emit(static_cast<uint8_t>(op));
}

// Little-endian 32-bit integer
void Compiler::emitInt32(int32_t val) {
    emit( val        & 0xFF);
    emit((val >>  8) & 0xFF);
    emit((val >> 16) & 0xFF);
    emit((val >> 24) & 0xFF);
}

// Little-endian 16-bit unsigned integer
void Compiler::emitUInt16(uint16_t val) {
    emit( val       & 0xFF);
    emit((val >> 8) & 0xFF);
}

// ─────────────────────────────────────────────
//  Jump backpatching
// ─────────────────────────────────────────────

// Emit the jump opcode followed by a 4-byte placeholder (0xDEADBEEF).
// Returns the byte-offset of the placeholder so we can patch it later.
int Compiler::emitJump(Opcode jumpOp) {
    emitOpcode(jumpOp);
    int placeholderPos = static_cast<int>(code.size());
    emitInt32(0x00DEAD00);   // placeholder
    return placeholderPos;
}

// Write the current code size (= the address of the next instruction
// after the jump body) into the 4-byte slot we reserved earlier.
void Compiler::patchJump(int jumpPos) {
    int32_t target = static_cast<int32_t>(code.size());
    code[jumpPos + 0] =  target        & 0xFF;
    code[jumpPos + 1] = (target >>  8) & 0xFF;
    code[jumpPos + 2] = (target >> 16) & 0xFF;
    code[jumpPos + 3] = (target >> 24) & 0xFF;
}

// ─────────────────────────────────────────────
//  AST node dispatch
// ─────────────────────────────────────────────

void Compiler::compileNode(ASTNode* node) {
    // We use dynamic_cast<> to determine the concrete node type.
    // (A visitor pattern would also work; dynamic_cast is simpler
    //  for a project of this scope.)

    if (auto n = dynamic_cast<Block*>(node))
        compileBlock(n);

    else if (auto n = dynamic_cast<LetStatement*>(node))
        compileLetStatement(n);

    else if (auto n = dynamic_cast<AssignStatement*>(node))
        compileAssignStatement(n);

    else if (auto n = dynamic_cast<IfStatement*>(node))
        compileIfStatement(n);

    else if (auto n = dynamic_cast<WhileStatement*>(node))
        compileWhileStatement(n);

    else if (auto n = dynamic_cast<PrintStatement*>(node))
        compilePrintStatement(n);

    else if (auto n = dynamic_cast<InputStatement*>(node))
        compileInputStatement(n);

    else if (auto n = dynamic_cast<BinaryExpr*>(node))
        compileBinaryExpr(n);

    else if (auto n = dynamic_cast<UnaryExpr*>(node))
        compileUnaryExpr(n);

    // ── Leaf nodes ──────────────────────────────────────────

    else if (auto n = dynamic_cast<NumberLiteral*>(node)) {
        emitOpcode(Opcode::PUSH_INT);
        emitInt32(n->value);
    }
    else if (auto n = dynamic_cast<BoolLiteral*>(node)) {
        emitOpcode(Opcode::PUSH_BOOL);
        emit(n->value ? 1 : 0);
    }
    else if (auto n = dynamic_cast<Identifier*>(node)) {
        emitOpcode(Opcode::LOAD);
        emitUInt16(getOrAddName(n->name));
    }
    else {
        throw std::runtime_error("Compiler: unknown AST node type");
    }
}

// ─────────────────────────────────────────────
//  Statement compilers
// ─────────────────────────────────────────────

// A block just compiles each of its children in order.
void Compiler::compileBlock(Block* node) {
    for (auto& stmt : node->statements)
        compileNode(stmt.get());
}

// let x = expr;
//   compile expr        → value lands on stack top
//   STORE x             → pop and save
void Compiler::compileLetStatement(LetStatement* node) {
    compileNode(node->initializer.get());
    emitOpcode(Opcode::STORE);
    emitUInt16(getOrAddName(node->name));
}

// x = expr;   (same as let, just no new declaration)
void Compiler::compileAssignStatement(AssignStatement* node) {
    compileNode(node->value.get());
    emitOpcode(Opcode::STORE);
    emitUInt16(getOrAddName(node->name));
}

// if (cond) { then } else { else }
//
// Generated bytecode layout:
//
//   [ compile condition ]
//   JUMP_IF_FALSE  → afterThen
//   [ compile thenBranch ]
//   JUMP           → afterElse      ← only emitted when else exists
//  afterThen:
//   [ compile elseBranch ]           ← may be empty
//  afterElse:
//
void Compiler::compileIfStatement(IfStatement* node) {
    compileNode(node->condition.get());

    int jumpIfFalsePos = emitJump(Opcode::JUMP_IF_FALSE); // → afterThen

    compileNode(node->thenBranch.get());

    if (node->elseBranch) {
        int jumpOverElsePos = emitJump(Opcode::JUMP);    // → afterElse
        patchJump(jumpIfFalsePos);                        // afterThen = here
        compileNode(node->elseBranch.get());
        patchJump(jumpOverElsePos);                       // afterElse = here
    } else {
        patchJump(jumpIfFalsePos);                        // afterThen = here
    }
}

// while (cond) { body }
//
// Generated bytecode layout:
//
//  loopStart:
//   [ compile condition ]
//   JUMP_IF_FALSE  → afterLoop
//   [ compile body ]
//   JUMP           → loopStart    (absolute address)
//  afterLoop:
//
void Compiler::compileWhileStatement(WhileStatement* node) {
    int loopStart = static_cast<int>(code.size());

    compileNode(node->condition.get());

    int jumpOutPos = emitJump(Opcode::JUMP_IF_FALSE); // → afterLoop

    compileNode(node->body.get());

    // Unconditional jump back to the top of the loop
    emitOpcode(Opcode::JUMP);
    emitInt32(loopStart);

    patchJump(jumpOutPos); // afterLoop = here
}

// print expr;
//   compile expr → value on stack
//   PRINT        → pop and output
void Compiler::compilePrintStatement(PrintStatement* node) {
    compileNode(node->expr.get());
    emitOpcode(Opcode::PRINT);
}

// input varName;
//   INPUT varName → VM reads stdin and stores into the variable
void Compiler::compileInputStatement(InputStatement* node) {
    emitOpcode(Opcode::INPUT);
    emitUInt16(getOrAddName(node->varName));
}

// ─────────────────────────────────────────────
//  Expression compilers
// ─────────────────────────────────────────────

// Binary expression: compile both sides, then emit the operator.
// Stack effect: (a, b) → result
void Compiler::compileBinaryExpr(BinaryExpr* node) {
    compileNode(node->left.get());   // push left operand
    compileNode(node->right.get());  // push right operand

    // Map operator string → opcode
    if      (node->op == "+")  emitOpcode(Opcode::ADD);
    else if (node->op == "-")  emitOpcode(Opcode::SUB);
    else if (node->op == "*")  emitOpcode(Opcode::MUL);
    else if (node->op == "/")  emitOpcode(Opcode::DIV);
    else if (node->op == "==") emitOpcode(Opcode::EQ);
    else if (node->op == "!=") emitOpcode(Opcode::NEQ);
    else if (node->op == "<")  emitOpcode(Opcode::LT);
    else if (node->op == "<=") emitOpcode(Opcode::LEQ);
    else if (node->op == ">")  emitOpcode(Opcode::GT);
    else if (node->op == ">=") emitOpcode(Opcode::GEQ);
    else throw std::runtime_error(
        "Compiler: unknown binary operator '" + node->op + "'");
}

// Unary expression: compile operand, then emit the operator.
void Compiler::compileUnaryExpr(UnaryExpr* node) {
    compileNode(node->operand.get());
    if (node->op == "-") emitOpcode(Opcode::NEGATE);
    else throw std::runtime_error(
        "Compiler: unknown unary operator '" + node->op + "'");
}